language: cpp
dist: trusty
compiler: g++
os: linux
sudo: required

env:
  - GCC_VERSION=5
  - GCC_VERSION=6

addons: &gcc5
  apt:
    packages:
      - g++-5
      - gcc-5
      - gcc-6
      - g++-6
      - libeigen3-dev 
      - libboost-all-dev
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - mkdir -p include
  - curl -o include/catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - sudo add-apt-repository ppa:kylelutz/compute -y
  - sudo apt-get update -q
  - sudo apt-get -y install boost-compute opencl-headers ocl-icd-opencl-dev
  - sudo cp -r /usr/include/compute/boost/* /usr/include/boost
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
    fi;
  - sudo rm /usr/bin/g++
  - if [ $GCC_VERSION = 5 ]; then
      sudo ln -s /usr/bin/g++-5 /usr/bin/g++;
    fi;
  - if [ $GCC_VERSION = 6 ]; then
      sudo ln -s /usr/bin/g++-6 /usr/bin/g++;
    fi;
  - sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
  
script:
  - cmake . -DUSE_ADDRESS_SANITIZER=0
  - make VERBOSE=1
